language: ruby
rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.0
  - ruby-head
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - bundle exec bin/kaede dbus-policy $USER > kaede.conf
  - sudo mv kaede.conf /etc/dbus-1/system.d/kaede.conf
  - psql -c "CREATE ROLE kaede WITH LOGIN" -U postgres
  - psql -c "CREATE DATABASE kaede_test WITH OWNER = kaede ENCODING = 'UTF-8' TEMPLATE = template0" -U postgres
matrix:
  allow_failures:
    - rvm: ruby-head
