language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - psql -c "CREATE ROLE kaede WITH LOGIN" -U postgres
  - psql -c "CREATE DATABASE kaede_test WITH OWNER = kaede ENCODING = 'UTF-8' TEMPLATE = template0" -U postgres
matrix:
  allow_failures:
    - rvm: ruby-head
