language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - psql -c "CREATE ROLE kaede WITH LOGIN" -U postgres
  - psql -c "CREATE DATABASE kaede_test WITH OWNER = kaede ENCODING = 'UTF-8' TEMPLATE = template0" -U postgres
matrix:
  allow_failures:
    - rvm: ruby-head
