# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kaede/grpc/kaede.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "kaede.grpc.SchedulerReloadInput" do
  end
  add_message "kaede.grpc.SchedulerReloadOutput" do
  end
  add_message "kaede.grpc.SchedulerStopInput" do
  end
  add_message "kaede.grpc.SchedulerStopOutput" do
  end
  add_message "kaede.grpc.GetProgramsInput" do
  end
  add_message "kaede.grpc.GetProgramsOutput" do
    repeated :programs, :message, 1, "kaede.grpc.Program"
  end
  add_message "kaede.grpc.AddTidInput" do
    optional :tid, :uint32, 1
  end
  add_message "kaede.grpc.AddTidOutput" do
    optional :tid, :uint32, 1
    optional :title, :string, 2
  end
  add_message "kaede.grpc.UpdateInput" do
  end
  add_message "kaede.grpc.UpdateOutput" do
  end
  add_message "kaede.grpc.AddChannelInput" do
    optional :name, :string, 1
    optional :recorder, :uint32, 2
    optional :syoboi, :uint32, 3
  end
  add_message "kaede.grpc.AddChannelOutput" do
  end
  add_message "kaede.grpc.Program" do
    optional :pid, :uint32, 1
    optional :tid, :uint32, 2
    optional :start_time, :message, 3, "google.protobuf.Timestamp"
    optional :end_time, :message, 4, "google.protobuf.Timestamp"
    optional :channel_name, :string, 5
    optional :channel_for_syoboi, :uint32, 6
    optional :channel_for_recorder, :uint32, 7
    optional :count, :string, 8
    optional :start_offset, :int32, 9
    optional :subtitle, :string, 10
    optional :title, :string, 11
    optional :comment, :string, 12
    optional :enqueued_at, :message, 13, "google.protobuf.Timestamp"
  end
end

module Kaede
  module Grpc
    SchedulerReloadInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.SchedulerReloadInput").msgclass
    SchedulerReloadOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.SchedulerReloadOutput").msgclass
    SchedulerStopInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.SchedulerStopInput").msgclass
    SchedulerStopOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.SchedulerStopOutput").msgclass
    GetProgramsInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.GetProgramsInput").msgclass
    GetProgramsOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.GetProgramsOutput").msgclass
    AddTidInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.AddTidInput").msgclass
    AddTidOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.AddTidOutput").msgclass
    UpdateInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.UpdateInput").msgclass
    UpdateOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.UpdateOutput").msgclass
    AddChannelInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.AddChannelInput").msgclass
    AddChannelOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.AddChannelOutput").msgclass
    Program = Google::Protobuf::DescriptorPool.generated_pool.lookup("kaede.grpc.Program").msgclass
  end
end
